import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Moon, Sun } from 'lucide-react';
import { Planner } from '@/components/tools/Planner';
import { GuideCard } from '@/components/content/GuideCard';
import { articles, quests } from '@/content/data';
import { SITE_NAME, SITE_URL } from '@/lib/site';

const needs = [
  {question:"I don't know what quest to do next",title:'Quest Order',href:'/guides/quest-order/'},
  {question:"I'm afraid I'll miss something",title:'Missable Checklist',href:'/tools/missable-checklist/'},
  {question:'I need help with a choice',title:'Choices, Spoiler-Safe',href:'/tools/choices/'},
  {question:'My game runs badly',title:'Performance Help',href:'/fixes/'},
];
const problems = [
  {title:'What actually advances time?',description:'Exploration does not run down a real-time countdown. Certain quest actions spend time; check the displayed hourglass cost before committing.',href:'/guides/time-limit/'},
  {title:'Can this planner guarantee a complete run?',description:'No. It compares known costs for selected quests, while unknown costs and incomplete deadline information limit what the totals can tell you.',href:'/tools/30-day-planner/'},
  {title:'Which quests should I do first?',description:'Start with the prologue quest-order guide to compare reported costs and checkpoints. It covers selected opening quests, not a complete campaign route.',href:'/guides/quest-order/'},
  {title:'Which choices can I change later?',description:'Reversibility depends on the decision. Check the individual choice guide and keep an earlier save when a later reversal has not been established.',href:'/guides/choices/'},
];
export default function Home() {
  const updated = ['time-limit','combat','release-date'].map(slug => articles.find(a => a.slug === slug)).filter(a => a !== undefined);
  return <div className="wrap"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':SITE_URL+'/#website',url:SITE_URL,name:SITE_NAME,description:'A decision-first fan guide to The Blood of Dawnwalker.'},{'@type':'Organization','@id':SITE_URL+'/#organization',name:SITE_NAME,url:SITE_URL,description:'Independent, unofficial fan resource.'}]}).replace(/</g,'\\u003c')}}/><div className="hero"><div className="hero-eclipse" aria-hidden="true"><div className="ring"/><div className="core"/></div><div className="kicker">Two Worlds · One Choice</div><h1>Blood of Dawnwalker Guide &amp; <em>30-Day Planner</em></h1><p>Use this Blood of Dawnwalker guide to check prologue quest order, compare choices and review reported missable moments. Add quests to the planner to compare known time costs, with spoilers under your control.</p><div className="hero-actions"><Link href="/tools/30-day-planner/" className="btn btn-primary">Build My Route <ArrowRight size={16}/></Link><Link href="/guides/missable-quests/" className="btn btn-outline">See Missable Quests</Link></div><div className="duality"><span><Sun size={14}/><b>Human by day</b> — sword & witchcraft</span><span><Moon size={14}/><b>Vampire by night</b> — claws & new paths</span></div></div>
  <section className="home-section"><div className="section-heading"><h2>What Do You Need Right Now?</h2></div><div className="need-grid">{needs.map((need,i) => <Link key={need.href} href={need.href} className="need-card"><div className="need-number">0{i+1}</div><h3>{need.question}</h3><span>{need.title} →</span></Link>)}</div></section>
  <section className="home-section" id="planner"><div className="section-heading"><h2>30-Day Planner</h2><Link className="section-more" href="/guides/time-limit/">Small decisions. Limited time. Understand the clock ↗</Link></div><Planner quests={quests} compact/><p className="section-note">Your plan stays in this browser. Coverage currently focuses on selected prologue quests and a small number of later decisions. Unknown costs remain unknown, and the planner does not provide a verified full-campaign route.</p></section>
  <section className="home-section" id="start-here"><div className="section-heading"><h2>Blood of Dawnwalker Guide: Where to Start</h2><Link href="/guides/" className="section-more">Explore the guides →</Link></div><div className="problem-grid">{problems.map(problem => <Link key={problem.href} href={problem.href} className="problem-card"><div><h3>{problem.title}</h3><p>{problem.description}</p></div><ArrowUpRight size={17}/></Link>)}</div></section>
  <section className="home-section" id="performance"><div className="section-heading"><h2>Performance Help &amp; Compatibility</h2><Link href="/fixes/" className="section-more">All performance help →</Link></div><div className="fix-grid">{[['Stuttering','stuttering','Official workaround'],['PC Settings','best-settings','General baseline checks'],['Crashing','crashing','General troubleshooting'],['Steam Deck','steam-deck','Not verified here'],['PS5 Performance','ps5','Performance not tested here']].map(([name,slug,detail]) => <Link href={`/fixes/${slug}/`} className="fix-card" key={slug}><h3>{name}</h3><small>{detail}</small></Link>)}</div></section>
  <section className="home-section" id="recent-guides"><div className="section-heading"><h2>Recently Updated Guides</h2><Link href="/editorial-policy/" className="section-more">Our verification policy →</Link></div><div className="guide-grid">{updated.map(article => <GuideCard key={article.slug} article={article}/>)}</div><p className="section-note">“Officially confirmed” refers to the cited source. We have not independently tested the retail build.</p></section><section className="home-section" id="sources"><div className="section-heading"><h2>Sources &amp; Coverage</h2><Link className="section-more" href="/editorial-policy/">How we check our guides →</Link></div><p>We use official material for game mechanics and identify published playthrough reports in individual guides. Start with <a className="text-link" href="https://en.bandainamcoent.eu/dawnwalker/news/explore-the-blood-of-dawnwalkers-features-ahead-of-release-new-gameplay-trailer">Bandai Namco’s official features overview</a> for the time system, then use our <Link className="text-link" href="/guides/beginner/">beginner guide</Link> and <Link className="text-link" href="/guides/quest-order/">prologue quest-order guide</Link> for practical next steps.</p><p className="section-note">This is an independent, unofficial fan guide. Coverage is selective; source confirmation is not a claim that we tested the retail build. Each guide separates reported facts, editorial advice and unknowns.</p></section></div>;
}
