import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { CalendarDays, CheckCheck, Eclipse, ArrowUpRight, Info } from 'lucide-react';
import { articles, choices, quests, missables } from '@/content/data';
import { ArticleView, Breadcrumbs, QuickAnswer, Sources, RelatedLinks } from '@/components/content/ArticleView';
import { GuideCard } from '@/components/content/GuideCard';
import { SupportView } from '@/components/content/SupportView';
import { VerifiedBadge } from '@/components/content/Trust';
import { SpoilerGate } from '@/components/site/Preferences';
import { Planner } from '@/components/tools/Planner';
import { Checklist } from '@/components/tools/Checklist';
import { ChoicesExplorer } from '@/components/tools/ChoicesExplorer';
import { hubs, supports, toolRoutes, getRouteKeys, routeTitle, isIndexable } from '@/lib/routes';
import { SITE_URL, SITE_NAME, absolute } from '@/lib/site';

export const dynamicParams = false;
export function generateStaticParams(){return getRouteKeys().map(key=>({slug:key.split('/')}));}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{
  const key=(await params).slug.join('/');const article=articles.find(a=>`${a.category}/${a.slug}`===key); const title=routeTitle(key); const path=`/${key}/`;const description=article?.description||hubs[key]?.description||`${title} for The Blood of Dawnwalker. Source-backed information, local progress, and spoiler controls from Dawnwalker Guide.`;
  return {title:{absolute: title.includes('Dawnwalker') ? title : title + ' | Dawnwalker Guide'},description,alternates:{canonical:path},robots:{index:isIndexable(key),follow:true},openGraph:{title,description,url:absolute(path),type:article?'article':'website',siteName:SITE_NAME,images:[{url:absolute(`/og/${key}.png`),width:1200,height:630}]},twitter:{card:'summary_large_image',title,description,images:[absolute(`/og/${key}.png`)]}};
}
function StructuredData({route}:{route:string}){const article=articles.find(a=>`${a.category}/${a.slug}`===route);const path=`/${route}/`;const title=routeTitle(route);const graph:Record<string,unknown>[]=[{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE_URL},{'@type':'ListItem',position:2,name:title,item:absolute(path)}]}];if(article)graph.push({'@type':'Article',headline:title,description:article.description,dateModified:article.updated+'T00:00:00+08:00',author:{'@type':'Organization',name:SITE_NAME,url:SITE_URL},publisher:{'@type':'Organization',name:SITE_NAME,url:SITE_URL},mainEntityOfPage:absolute(path),image:absolute(`/og/${route}.png`)});if(toolRoutes.includes(route))graph.push({'@type':'WebApplication',name:title,url:absolute(path),applicationCategory:'GameApplication',operatingSystem:'Any',browserRequirements:'Requires JavaScript; local storage optional',isAccessibleForFree:true});return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c')}}/>;}
function PageIntro({title,description,kicker='THE BLOOD OF DAWNWALKER',parent='Guides',parentHref='/guides/'}:{title:string;description?:string;kicker?:string;parent?:string;parentHref?:string}) {return <div className="page-intro"><Breadcrumbs items={[{title:parent,href:parentHref},{title}]}/><p className="eyebrow">{kicker}</p><h1>{title}</h1>{description&&<p>{description}</p>}</div>;}
function ToolCards(){const tools=[{href:'/tools/30-day-planner/',title:'30-Day Planner',text:'Keep the next quest in sight. Add quests, check time costs, and review what is still unknown.',Icon:CalendarDays},{href:'/tools/missable-checklist/',title:'Missable Checklist',text:'Keep a personal record of the reported time-sensitive moments you have checked.',Icon:CheckCheck},{href:'/tools/choices/',title:'Spoiler-Controlled Choices',text:'Get a recommendation now. Reveal a little context, or the full reported outcome.',Icon:Eclipse}];return <div className="hub-tools">{tools.map(({href,title,text,Icon})=><div className="card" key={href}><Icon size={25}/><h2>{title}</h2><p>{text}</p><Link className="text-link" href={href}>Open tool →</Link></div>)}</div>;}
function Hub({route}:{route:string}){const hub=hubs[route];let selected=articles.filter(a=>a.category==='guides'&&!a.slug.includes('/'));if(route==='fixes')selected=articles.filter(a=>a.category==='fixes');if(route==='news')selected=articles.filter(a=>a.category==='news');if(route==='guides/bosses'||route==='guides/builds')selected=articles.filter(a=>['combat','beginner','quest-order'].includes(a.slug));
 return <div className="wrap page-shell"><PageIntro title={hub.title} description={hub.description} parent="Explore" parentHref="/" kicker={route.replaceAll('/',' · ')}/>{route==='tools'?<ToolCards/>:route==='guides/quests'?<><div className="info-strip"><Info size={18}/><span>Quest reference · Reported by external playthrough authors · An unknown value does not mean zero.</span></div><div className="guide-grid">{quests.map(q=><Link className="guide-card" key={q.slug} href={`/guides/quests/${q.slug}/`}><VerifiedBadge status={q.verificationStatus}/><h3>{q.name}</h3><p>{q.spoilerSafeSummary}</p><div className="card-meta">{q.timeCost===null?'Time cost varies / unknown':`${q.timeCost} reported segment${q.timeCost!==1?'s':''}`} · {q.routeTags.includes('prologue') ? 'Prologue' : 'Later campaign'}</div></Link>)}</div></>:route==='updates'?<div className="support-copy"><h2>September 5, 2026 — First field edition</h2><p>The initial guide contains a small source-linked prologue database, three decision comparisons, a local planner and checklist, and official launch / hotfix context.</p><p>No full-campaign route, retail hardware benchmarks, or boss attack database has been independently tested. Unknown costs and consequences remain explicit.</p><h2>What is next</h2><p>Coverage expands when original evidence can answer a specific player question. The <Link href="/editorial-policy/">editorial policy</Link> defines the publishing standard.</p><Link href="/news/" className="text-link">Read official update context →</Link></div>:<>{(route==='guides/bosses'||route==='guides/builds')&&<div className="unknown" style={{marginBottom:24}}>Specific boss walkthroughs and optimized builds are not published yet. These documented system guides can help you prepare; they are not a substitute for verified encounter data.</div>}{route==='guides'&&<ToolCards/>}{route==='news'&&!selected.length?<div className="card support-copy"><p className="eyebrow">Official update · September 4, 2026</p><h2>Hotfix 1.0.2: check the issue, not just the version</h2><p>The official patch note lists remaining issues and a fullscreen workaround. A patch number alone does not establish that a particular crash or performance problem has been fixed.</p><a className="text-link" href="https://dawnwalkergame.com/us/en/news/hotfix-102" target="_blank" rel="noreferrer">Read the original developer note ↗</a><p><Link href="/fixes/">See the troubleshooting guides →</Link></p></div>:<div className="guide-grid">{selected.map(a=><GuideCard key={`${a.category}/${a.slug}`} article={a}/>)}</div>}</>}</div>;
}
function QuestView({slug}:{slug:string}) {const q=quests.find(q=>q.slug===slug);if(!q)notFound();const relatedChoices=choices.filter(c=>c.questSlug===slug);const rows=[['Type',q.type],['Location',q.location||'Unknown'],['Time cost',q.timeCost===null?'Unknown / conditional — check the hourglass':`${q.timeCost} reported segment(s)`],['Day / night',q.timeOfDay],['Missable',q.missable===null?'Unknown':q.missable?'Reported risk':'No deadline established'],['Deadline',q.deadline||'Not verified'],['Prerequisites',q.prerequisites.join(', ')||'Not verified']];return <div className="wrap page-shell"><PageIntro title={`${q.name} — Quest Reference`} description="A concise, source-linked reference. Confirm the details against your in-game journal." parent="Quests" parentHref="/guides/quests/"/><div className="support-copy"><QuickAnswer text={q.spoilerSafeSummary} status={q.verificationStatus} version={q.gameVersion}/><div className="table-wrap"><table className="overview-table"><tbody>{rows.map(([key,value])=><tr key={key}><th scope="row">{key}</th><td>{value}</td></tr>)}</tbody></table></div><section className="article-section"><h2>Before you commit</h2><p>{q.howToStart}</p><p>Read the hourglass in your game before accepting a time-costing action. {q.routeTags.includes('prologue') ? 'This reference covers the prologue; do not subtract its cost from a later campaign calendar.' : 'This is a later campaign quest. Its total cost is not yet established.'}</p></section><section className="article-section"><h2>Reward notes</h2><SpoilerGate level="light"><p>{q.rewards.length?q.rewards.join(' · '):'Reward details are not verified.'}</p></SpoilerGate></section><div className="warning"><strong>Check time-sensitive content</strong>{q.deadline||'An unknown deadline is not a guarantee that you can return later. Check your journal and the cited source.'}</div><Sources sources={q.sources}/><RelatedLinks links={[{href:'/tools/30-day-planner/',title:'Add quests to your planner'},{href:'/guides/quest-order/',title:'Prologue quest order'},...relatedChoices.map(c=>({href:`/guides/choices/${c.slug}/`,title:c.question}))]}/></div></div>;}
function ChoiceView({slug}:{slug:string}) {const choice=choices.find(c=>c.slug===slug);if(!choice)notFound();return <div className="wrap page-shell"><PageIntro title={choice.title} parent="Choices" parentHref="/guides/choices/" kicker="A choice, on your terms"/><div className="support-copy choice-details"><QuickAnswer text={choice.recommendation} status={choice.verificationStatus} version="Published playthrough report · Retail version not specified"/><>{choice.checkpoints && <section><h2>Before the banner decision</h2><ol className="article-steps">{choice.checkpoints.map(step => <li key={step}>{step}</li>)}</ol><p className="reviewed-note">Decision checklist by our editors, based on the playthrough source below. The quest total and the extra cost of an individual branch are different values; branch costs remain unknown here.</p></section>}</><section><h2>Compare your options</h2><div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Option</th><th>Recommended for</th><th>Time cost</th></tr></thead><tbody>{choice.options.map(o=><tr key={o.label}><td>{o.label}</td><td>{o.bestFor}</td><td>{o.timeCost===null?'Unknown':`${o.timeCost} segments`}</td></tr>)}</tbody></table></div></section><section><h2 style={{marginBottom:16}}>A little more context</h2><SpoilerGate level="light"><p>{choice.lightConsequence}</p></SpoilerGate></section><section><h2 style={{marginBottom:16}}>Full reported consequences</h2><SpoilerGate level="full"><p>{choice.fullConsequence}</p><div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>Option</th><th>Reported reward</th><th>Reported consequence</th></tr></thead><tbody>{choice.options.map(o=><tr key={o.label}><td>{o.label}</td><td>{o.reward}</td><td>{o.lockout}</td></tr>)}</tbody></table></div></SpoilerGate></section><section><h2>Can you change this later?</h2><p>{choice.reversible}</p></section><Sources sources={choice.sources}/><RelatedLinks links={[{href:quests.some(q=>q.slug===choice.questSlug)?`/guides/quests/${choice.questSlug}/`:'/guides/choices/',title:quests.some(q=>q.slug===choice.questSlug)?'Read the related quest reference':'Read the choices guide'},{href:'/tools/missable-checklist/',title:'Review your missable checklist'}]}/></div></div>;}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const route=(await params).slug.join('/');if(!getRouteKeys().includes(route))notFound();let content:React.ReactNode;const article=articles.find(a=>`${a.category}/${a.slug}`===route);
 if(supports.includes(route))content=<SupportView kind={route}/>;
 else if(toolRoutes.includes(route))content=<div className="wrap page-shell"><PageIntro title={routeTitle(route)} description={route.endsWith('30-day-planner')?'Choose your next quests. See the time cost, keep the unknowns visible, and save your plan here.':route.endsWith('missable-checklist')?'A personal checklist for reported missable moments. Start with the prologue; reveal details only when you need them.':'One decision at a time. Compare options without reading further into the story than you want.'} parent="Tools" parentHref="/tools/" kicker="Your playthrough, your pace"/>{route.endsWith('30-day-planner')?<Planner quests={quests}/>:route.endsWith('missable-checklist')?<Checklist items={missables}/>:<ChoicesExplorer choices={choices} quests={quests}/>}</div>;
 else if(route.startsWith('guides/choices/'))content=<ChoiceView slug={route.slice('guides/choices/'.length)}/>;
 else if(article)content=<><ArticleView article={article} quest={route.startsWith('guides/quests/') ? quests.find(q=>q.slug === route.slice('guides/quests/'.length)) : undefined} related={article.related.filter(h=>getRouteKeys().includes(h.replace(/^\/+|\/+$/g,''))).map(h=>({href:h,title:routeTitle(h)}))}/>{route==='guides/choices'&&<div className="wrap" style={{paddingBottom:50}}><ChoicesExplorer choices={choices} quests={quests}/></div>}</>;
 else if(hubs[route])content=<Hub route={route}/>;
 else if(route.startsWith('guides/quests/'))content=<QuestView slug={route.slice('guides/quests/'.length)}/>;
 else notFound();return <><StructuredData route={route}/>{content}</>;
}
