import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const base='http://127.0.0.1:3000';
await fs.mkdir('artifacts',{recursive:true});
const manifest=JSON.parse(await fs.readFile('.next/prerender-manifest.json','utf8'));
const routes=Object.keys(manifest.routes).filter(p=>!p.startsWith('/og/')&&!p.startsWith('/_')&&!['/opengraph-image','/robots.txt','/sitemap.xml','/feed.xml','/icon.svg'].includes(p));
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[];const checks=[];const broken=[];const links=new Set();
let expected404=false;
page.on('pageerror',error=>errors.push(error.message));
page.on('console',msg=>{if(msg.type()==='error'&&!(expected404&&msg.text().includes('404 (Not Found)')))errors.push(msg.text());});
const note=(name,detail=true)=>{checks.push({name,detail});console.log('PASS',name);};
try{
  for(const path of routes){
    const response=await page.goto(base+path);assert.equal(response.status(),200,path);await page.waitForLoadState('networkidle');
    assert.equal(await page.locator('h1').count(),1,`one H1: ${path}`);
    const canonical=await page.locator('link[rel="canonical"]').getAttribute('href');assert.equal(canonical,'https://dawnwalker-guide.wiki'+(path==='/'?'/':path.replace(/\/$/,'')+'/'),path);
    assert.ok((await page.title()).length>10);assert.ok((await page.locator('meta[name="description"]').getAttribute('content')).length>30);
    for(const link of await page.locator('a[href]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href'))))if(link.startsWith('/')&&!link.startsWith('//'))links.add(link.split('#')[0].split('?')[0]);
    for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));if(sizes.scroll>sizes.width+1)broken.push({path,width,...sizes});}
    await page.setViewportSize({width:1440,height:1000});
  }
  assert.deepEqual(broken,[],'responsive overflow');note('All '+routes.length+' page routes: HTTP, H1, canonical, description, desktop/mobile overflow');
  for(const path of links){const res=await context.request.get(base+path);assert.equal(res.status(),200,`internal link ${path}`);}note('All '+links.size+' internal destinations return 200');
  const sitemap=await (await context.request.get(base+'/sitemap.xml')).text();assert.ok(!sitemap.includes('/fixes/best-settings/'));assert.ok(!sitemap.includes('/guides/bosses/'));assert.ok(sitemap.includes('/guides/time-limit/'));note('Sitemap excludes unsupported pages');
  const robots=await (await context.request.get(base+'/robots.txt')).text();assert.ok(robots.includes('https://dawnwalker-guide.wiki/sitemap.xml'));const feed=await context.request.get(base+'/feed.xml');assert.equal(feed.status(),200);note('Robots and RSS');
  expected404=true;const missing=await page.goto(base+'/a-page-that-does-not-exist/');assert.equal(missing.status(),404);await page.waitForLoadState('networkidle');assert.match(await page.locator('body').innerText(),/path not yet charted/i);expected404=false;note('Custom 404');
  await page.goto(base+'/');await page.waitForLoadState('networkidle');
  await page.getByRole('button',{name:'Switch to day theme'}).click();assert.equal(await page.locator('html').getAttribute('data-theme'),'day');await page.reload();await page.waitForLoadState('networkidle');assert.equal(await page.locator('html').getAttribute('data-theme'),'day');await page.screenshot({path:'artifacts/home-day-desktop.png',fullPage:true,animations:'disabled'});note('Day theme persists after reload');
  await page.getByRole('button',{name:'Switch to night theme'}).click();await page.screenshot({path:'artifacts/home-night-desktop.png',fullPage:true,animations:'disabled'});
  await page.keyboard.press('Control+k');await page.getByRole('textbox',{name:'Search quests, choices and fixes'}).fill('stutter');assert.ok(await page.locator('.search-results a').count()>0);await page.getByRole('textbox',{name:'Search quests, choices and fixes'}).fill('zzzznoanswer123');assert.ok(await page.getByRole('heading',{name:'No answer yet'}).isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('.search-dialog').isVisible(),false);note('Keyboard search, matching results, empty state, Escape');
  await page.goto(base+'/tools/30-day-planner/');await page.waitForLoadState('networkidle');await page.getByRole('button',{name:'Show reported quests'}).click();
  const add=page.getByRole('button',{name:'Add Withering Away to plan'});await add.click();await page.getByRole('button',{name:'Add Live Bait to plan'}).click();assert.match(await page.locator('.plan-sidebar').innerText(),/unknown time cost/);assert.match(await page.locator('.plan-sidebar').innerText(),/No campaign days deducted/);
  await page.reload();await page.waitForLoadState('networkidle');assert.deepEqual((await page.evaluate(()=>JSON.parse(localStorage.getItem('dw-plan')))).sort(),['live-bait','withering-away']);note('Planner add, unknown costs, prologue isolation, reload persistence');
  await page.getByLabel('Current progress').selectOption('campaign');assert.ok(await page.getByLabel('Current day',{exact:true}).isVisible());await page.getByLabel('Current day',{exact:true}).fill('30');await page.getByRole('combobox',{name:'Current phase',exact:true}).selectOption('night');await page.getByRole('combobox',{name:'Segments used this phase'}).selectOption('7');assert.match(await page.locator('.plan-sidebar').innerText(),/excluded from this stage/);assert.equal(await page.locator('.plan-numbers strong').last().innerText(),'1');note('Final campaign segment arithmetic and exclusion');
  await page.getByRole('button',{name:'Add The Heart Wants What It Wants to plan'}).click();assert.match(await page.locator('.plan-sidebar').innerText(),/Balance unknown/);await page.getByRole('button',{name:'Remove The Heart Wants What It Wants from plan',exact:true}).last().click();
  await page.getByLabel('Current progress').selectOption('prologue');await page.getByRole('button',{name:'Romance',exact:true}).click();assert.equal(await page.locator('.quest-table tbody tr').first().locator('.quest-name').innerText(),'Page-Turner');await page.getByRole('button',{name:'Best Equipment',exact:true}).click();note('Planning goals and campaign unknown cost');
  await page.getByRole('button',{name:'See Most Content',exact:true}).click();await page.screenshot({path:'artifacts/planner-desktop.png',fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});await page.locator('.filter-trigger').first().click();assert.ok(await page.locator('.filter-dialog').isVisible());await page.keyboard.press('Escape');await page.locator('.mobile-plan-toggle').click();assert.ok(await page.locator('.mobile-plan-content').isVisible());await page.screenshot({path:'artifacts/planner-mobile.png',fullPage:true,animations:'disabled'});note('Mobile filter drawer and expandable plan summary');
  await page.goto(base+'/tools/missable-checklist/');await page.waitForLoadState('networkidle');await page.locator('#check-gremla-banner').check();await page.reload();await page.waitForLoadState('networkidle');assert.equal(await page.locator('#check-gremla-banner').isChecked(),true);assert.ok(!await page.locator('body').innerText().then(t=>t.includes('Gremla’s death')));note('Checklist persistence and default spoiler protection');
  await page.goto(base+'/guides/choices/blasphemy-return-the-banner/');await page.waitForLoadState('networkidle');assert.ok(!(await page.locator('body').innerText()).includes('Gremla dies'));await page.getByRole('button',{name:'Full spoilers',exact:true}).last().click();assert.match(await page.locator('body').innerText(),/Gremla dies/);await page.reload();await page.waitForLoadState('networkidle');assert.match(await page.locator('body').innerText(),/Gremla dies/);await page.getByRole('button',{name:'No spoilers',exact:true}).last().click();assert.ok(!(await page.locator('body').innerText()).includes('Gremla dies'));note('Full spoiler reveal, persistence, and rehide');
  await page.goto(base+'/tools/choices/');assert.ok(await page.getByText('Editorial: favor returning it', {exact:false}).isVisible());assert.ok(!(await page.locator('body').innerText()).includes('Gremla dies'));note('Choices keep recommendation visible without consequences');
  await page.goto(base+'/');await page.waitForLoadState('networkidle');await page.getByRole('button',{name:'Open navigation'}).click();assert.ok(await page.locator('.mobile-drawer').isVisible());await page.locator('.mobile-drawer').getByRole('link',{name:'Fixes',exact:true}).click();await page.waitForURL('**/fixes/');assert.equal(await page.locator('.mobile-drawer').isVisible(),false);note('Mobile navigation links and close on route');
  await page.goto(base+'/guides/time-limit/');await page.getByRole('button',{name:'Switch to day theme'}).click();await page.screenshot({path:'artifacts/guide-day-mobile.png',fullPage:true,animations:'disabled'});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'artifacts/guide-day-desktop.png',fullPage:true,animations:'disabled'});note('Guide day theme responsive screenshots');
  for(const path of ['/opengraph-image','/og/guides/time-limit/']){const response=await context.request.get(base+path);assert.equal(response.status(),200);assert.match(response.headers()['content-type'],/image\/png/);await fs.writeFile('artifacts/'+(path==='/opengraph-image'?'og-home.png':'og-guide.png'),await response.body());}note('Root and detail share images');
  await page.goto(base+'/contact/');await page.getByLabel('Page or topic').fill('/guides/time-limit/');await page.getByLabel('What should be corrected?').fill('Test correction report with a reproducible observation.');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download correction report'}).click();assert.equal((await download).suggestedFilename(),'dawnwalker-correction.txt');assert.match(await page.getByRole('status').innerText(),/Nothing has been sent/);note('Correction report download without fake submission');
  const isolated=await browser.newContext({viewport:{width:390,height:844}});const malformed=await isolated.newPage();await malformed.addInitScript(()=>{localStorage.setItem('dw-plan','not-json');localStorage.setItem('dw-plan-day','999');localStorage.setItem('dw-spoiler','unsafe');});await malformed.goto(base+'/tools/30-day-planner/');await malformed.waitForLoadState('networkidle');assert.match(await malformed.locator('.planner').innerText(),/0/);await isolated.close();note('Corrupted stored values degrade safely');
  await page.goto(base+'/guides/quests/withering-away/');assert.match(await page.locator('#quest-overview').innerText(),/2 segments/);note('Detailed quest articles retain structured cost and deadline information');
  await page.goto(base+'/tools/missable-checklist/');await page.waitForLoadState('networkidle');assert.equal(await page.locator('#check-gremla-banner').isChecked(),true);const secondTab=await context.newPage();await secondTab.goto(base+'/');await secondTab.evaluate(()=>localStorage.clear());await page.waitForFunction(()=>!document.querySelector('#check-gremla-banner').checked);await page.waitForFunction(()=>document.documentElement.dataset.theme==='night');await secondTab.close();note('Cross-tab storage clear resets progress and preferences');
  await context.clearCookies();await page.goto(base+'/');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForLoadState('networkidle');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/home-night-mobile.png',fullPage:true,animations:'disabled'});
  assert.deepEqual(errors,[],'browser console/page errors');note('No JavaScript or console errors');
  await fs.writeFile('artifacts/browser-qa.json',JSON.stringify({checkedAt:new Date().toISOString(),base,routes:routes.length,internalLinks:links.size,checks,errors,broken},null,2));
}catch(error){await page.screenshot({path:'artifacts/qa-failure.png',fullPage:true,animations:'disabled'});await fs.writeFile('artifacts/browser-qa-failure.json',JSON.stringify({error:String(error),url:page.url(),checks,errors,broken},null,2));throw error;}finally{await browser.close();}
